#!/usr/bin/env python3
"""
tools/csv_to_wav.py (timestamp-aware)

Convert audio_samples.csv (generated by the simulator) into a WAV file.

This version respects the timestamp column (t_ps, picoseconds) emitted by the
testbench and fills WAV samples according to the requested samplerate.

Behavior:
 - If the CSV contains a 't_ps' column (case-insensitive), it will be used as
   event timestamps in picoseconds. The first timestamp is treated as t=0.
 - For each event (time, value) we hold the value from that time until the
   next event (sample-and-hold). This preserves exact event timing.
 - No external dependencies (numpy) required.
 - Options:
    --interp linear   : perform simple linear interpolation between events
    --col / --col-name: select value column (default: mo_signed)
    --scale           : scale factor before packing to int16 (default: 64)
    --preview N       : print first N interpolated samples and exit
"""
import argparse
import csv
import wave
import struct
import sys
import math
from typing import Optional, List, Tuple

def parse_args():
    p = argparse.ArgumentParser(description="Convert audio_samples.csv to WAV (timestamp-aware)")
    p.add_argument("-i", "--input", default="audio_samples.csv", help="Input CSV (default: audio_samples.csv)")
    p.add_argument("-o", "--output", default="out.wav", help="Output WAV (default: out.wav)")
    p.add_argument("--samplerate", type=int, default=44100, help="Output sample rate (Hz)")
    p.add_argument("--scale", type=float, default=64.0, help="Scale factor applied to sample values before packing to int16")
    p.add_argument("--col", type=int, help="Column index (0-based) to read samples from (overrides --col-name)")
    p.add_argument("--col-name", default="mo_signed", help="Column name to read samples from (default: mo_signed)")
    p.add_argument("--no-header", action="store_true", help="Treat CSV as having no header row")
    p.add_argument("--preview", type=int, help="Print first N output sample values and exit (no WAV written)")
    p.add_argument("--interp", choices=("hold","linear"), default="hold", help="Interpolation mode between events (default: hold)")
    p.add_argument("-q", "--quiet", action="store_true", help="Quiet mode")
    return p.parse_args()

def find_column_index(header_row, col_name) -> Optional[int]:
    for i, h in enumerate(header_row):
        if h.strip().lower() == col_name.strip().lower():
            return i
    # try fuzzy match containing substring
    for i, h in enumerate(header_row):
        if col_name.strip().lower() in h.strip().lower():
            return i
    return None

def clamp_int16(x: int) -> int:
    if x < -32768:
        return -32768
    if x > 32767:
        return 32767
    return x

def read_events(reader, col_index: int, has_header: bool) -> List[Tuple[int,int]]:
    """
    Read CSV reader and return list of (time_ps, value) tuples (time in ps).
    Expects that the CSV has either:
      - a t_ps column (when header present), or
      - if no header, the first column is t_ps (index 0) and value column specified by --col.
    """
    events = []
    # If header present, we expect a t_ps column. But we don't enforce: we try to find t_ps col by name.
    for row in reader:
        if not row:
            continue
        # attempt to parse a line robustly
        # if row shorter than expected, skip
        # We assume t_ps present at index 0 if header absent
        try:
            # the calling code should have determined col_index relative to header/no-header
            # but we still need t_ps index:
            if has_header:
                # header handled outside; here assume first column is t_ps if parsable
                tps_cell = row[0].strip()
            else:
                tps_cell = row[0].strip()
            # parse time (ps)
            t_ps = int(float(tps_cell))
        except Exception:
            # skip unparsable lines (e.g. header)
            continue
        # parse value from col_index
        if col_index is None or col_index >= len(row):
            continue
        cell = row[col_index].strip()
        if cell == "":
            continue
        try:
            sval = float(cell)
            ival = int(round(sval))
        except Exception:
            continue
        events.append((t_ps, ival))
    return events

def main():
    args = parse_args()
    infile = args.input
    outfile = args.output
    sr = args.samplerate
    scale = args.scale
    col_index = args.col
    col_name = args.col_name
    preview = args.preview
    no_header = args.no_header
    quiet = args.quiet
    interp_mode = args.interp

    try:
        f = open(infile, newline='')
    except FileNotFoundError:
        print(f"Input file not found: {infile}", file=sys.stderr)
        sys.exit(2)

    reader = csv.reader(f)
    header = None
    if not no_header:
        try:
            header = next(reader)
        except StopIteration:
            print("Empty CSV file", file=sys.stderr)
            sys.exit(2)

    # determine column index for value
    if col_index is None:
        if not no_header and header is not None:
            idx = find_column_index(header, col_name)
            if idx is None:
                # fallback: try to pick second column (index 1)
                if len(header) >= 2:
                    idx = 1
                    if not quiet:
                        print(f"Warning: column '{col_name}' not found in header; using column index 1", file=sys.stderr)
                else:
                    print(f"Cannot determine column for samples; header: {header}", file=sys.stderr)
                    sys.exit(2)
            col_index = idx
        else:
            print("When CSV has no header you must provide --col index", file=sys.stderr)
            sys.exit(2)

    if not quiet:
        print(f"Input: {infile}, Output: {outfile}, samplerate: {sr}, scale: {scale}, column: {col_index}, interp: {interp_mode}")

    # rewind and re-create reader to read all rows (we consumed header earlier)
    f.seek(0)
    reader = csv.reader(f)
    if not no_header:
        header = next(reader, None)

    events = read_events(reader, col_index, not no_header)
    if not events:
        print("No events parsed from CSV.", file=sys.stderr)
        f.close()
        sys.exit(2)

    # Ensure events sorted by time (should be)
    events.sort(key=lambda x: x[0])

    # Build sample buffer according to timestamps
    t0 = events[0][0]
    t_last = events[-1][0]
    duration_s = (t_last - t0) * 1e-12  # ps -> s
    if duration_s <= 0:
        print("Invalid duration parsed from CSV times.", file=sys.stderr)
        f.close()
        sys.exit(2)

    total_samples = int(math.ceil(duration_s * sr)) + 1
    if not quiet:
        print(f"Events: {len(events)}, duration: {duration_s:.6f} s, total_samples: {total_samples}")

    # Prepare an array of int16 samples (initialized to zero)
    samples = [0] * total_samples

    # Fill samples using sample-and-hold or linear interpolation
    for i in range(len(events)):
        t_ps, val = events[i]
        t_rel_s = (t_ps - t0) * 1e-12
        idx = int(round(t_rel_s * sr))
        if idx < 0:
            idx = 0
        if i + 1 < len(events):
            t_ps_next = events[i+1][0]
            t_rel_next_s = (t_ps_next - t0) * 1e-12
            idx_next = int(round(t_rel_next_s * sr))
            if idx_next < idx:
                idx_next = idx
        else:
            idx_next = total_samples

        # scaled integer value to write (clamped to int16 after scaling later)
        v = int(round(val * scale))

        if interp_mode == "hold":
            # fill [idx, idx_next) with v
            if idx < total_samples:
                end = min(idx_next, total_samples)
                for j in range(idx, end):
                    samples[j] = v
        else:  # linear interpolation
            # compute start value (current), end value (next event's value scaled) and fill linearly
            if i + 1 < len(events):
                v_next = int(round(events[i+1][1] * scale))
                length = max(1, idx_next - idx)
                for k in range(length):
                    frac = k / length
                    samples_idx = idx + k
                    if samples_idx >= total_samples:
                        break
                    samples[samples_idx] = int(round(v * (1.0 - frac) + v_next * frac))
            else:
                # last event: hold
                if idx < total_samples:
                    for j in range(idx, total_samples):
                        samples[j] = v

    # Optional preview
    if preview is not None:
        print("Preview first", preview, "samples:", samples[:preview])
        f.close()
        return

    # pack into WAV (mono 16-bit little endian)
    try:
        wf = wave.open(outfile, "wb")
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(sr)

        BATCH = 8192
        buf = bytearray()
        written = 0
        for i, s in enumerate(samples):
            s_clamped = clamp_int16(int(round(s)))
            buf.extend(struct.pack("<h", s_clamped))
            written += 1
            if written % BATCH == 0:
                wf.writeframes(buf)
                buf.clear()
        if buf:
            wf.writeframes(buf)
        wf.close()
        if not quiet:
            print(f"Wrote {outfile} ({written} frames)")
    finally:
        f.close()

if __name__ == "__main__":
    main()