#!/usr/bin/env python3
"""
CSV -> Verilog statements converter (pairwise addr/data) that emits wait_samples and schedule_write calls.

Usage:
  python3 tools/csv_to_verilog_initial_waitsamples.py events.csv [sample_rate]
Output:
  prints a Verilog statements file that uses wait_samples(<n>); schedule_write(8'hAA, 8'hBB);
Notes:
 - Keeps #0 semantics as wait_samples(0) (no sample wait) so multiple schedule_write in same sample are possible.
 - Safer for iverilog parsing (no huge `#` numeric literals).
"""
import sys, csv

if len(sys.argv) < 2:
    print("Usage: csv_to_verilog_initial_waitsamples.py <events.csv> [sample_rate]")
    sys.exit(1)

csvfile = sys.argv[1]
sample_rate = float(sys.argv[2]) if len(sys.argv) >= 3 else 44100.0

# sample_period_ps = 1e12 / sample_rate  # not needed for this mode

def parse_hex_token(tok):
    tok = tok.strip()
    if tok.lower().startswith("0x"):
        return int(tok, 16)
    try:
        return int(tok)
    except:
        try:
            return int(tok, 16)
        except:
            raise ValueError(f"cannot parse token: {tok}")

rows = []
with open(csvfile, newline='') as f:
    reader = csv.reader(f)
    first = next(reader)
    try:
        int(first[0])
        rows.append(first)
    except:
        pass
    for r in reader:
        if not r: continue
        rows.append(r)

print('// Generated by csv_to_verilog_initial_waitsamples.py')
print('// sample_rate = {}'.format(sample_rate))
print('// NOTE: emits wait_samples(n); schedule_write(addr,data); lines')
print()

i = 0
while i < len(rows):
    r = rows[i]
    if len(r) < 3:
        i += 1; continue
    try:
        delay_samples = int(r[0])
    except:
        i += 1; continue
    addr_val = parse_hex_token(r[2].strip())
    data_val = 0
    # look ahead for data row (delta==0)
    if i + 1 < len(rows):
        rn = rows[i+1]
        try:
            delta_next = int(rn[0])
            if delta_next == 0 and len(rn) >= 3:
                data_val = parse_hex_token(rn[2].strip())
                i += 2
            else:
                data_val = 0
                i += 1
        except:
            data_val = 0
            i += 1
    else:
        i += 1

    # Emit wait_samples(delay_samples) and schedule_write
    print(f'wait_samples({delay_samples});')
    print(f"schedule_write(8'h{addr_val:02X}, 8'h{data_val:02X});")

