`timescale 10ps/10ps
module IKAOPLL_tb;

// BUS IO wires
reg             EMUCLK = 1'b1;
reg             IC_n = 1'b1;
reg             CS_n = 1'b1;
reg             WR_n = 1'b1;
reg             A0 = 1'b0;
reg     [7:0]   DIN = 8'hZZ;

// generate clock
always #1 EMUCLK = ~EMUCLK;

reg     [1:0]   clkdiv = 2'd0;
reg             phiMref = 1'b0;
wire            phiM_PCEN_n = ~(clkdiv[1:0] == 2'b11);
always @(posedge EMUCLK) begin
    if (clkdiv == 2'd3) begin clkdiv <= 2'd0; phiMref <= 1'b1; end
    else clkdiv <= clkdiv + 2'd1;

    if (clkdiv[1:0] == 2'd1) phiMref <= 1'b0;
end

// async reset
initial begin
    #30 IC_n <= 1'b0;
    #1300 IC_n <= 1'b1;
end

// main chip
IKAOPLL #(
    .FULLY_SYNCHRONOUS          (1),
    .FAST_RESET                 (1),
    .ALTPATCH_CONFIG_MODE       (0),
    .USE_PIPELINED_MULTIPLIER   (1)
) main (
    .i_XIN_EMUCLK               (EMUCLK),
    .o_XOUT                     ( ),
    .i_phiM_PCEN_n              (1'b0),
    .i_IC_n                     (IC_n),
    .i_ALTPATCH_EN              (1'b0),
    .i_CS_n                     (CS_n),
    .i_WR_n                     (WR_n),
    .i_A0                       (A0),
    .i_D                        (DIN),
    .o_D                        ( ),
    .o_D_OE                     ( ),
    .o_DAC_EN_MO                ( ),
    .o_DAC_EN_RO                ( ),
    .o_IMP_NOFLUC_SIGN          ( ),
    .o_IMP_NOFLUC_MAG           ( ),
    .o_IMP_FLUC_SIGNED_MO       ( ),
    .o_IMP_FLUC_SIGNED_RO       ( ),
    .o_ACC_SIGNED_STRB          ( ),
    .o_ACC_SIGNED               ( )
);

// Simple non-ref variant for Icarus (use this from events generated by CSV)
// Manipulates TB signals directly (no ref ports) and uses phiMref as the sync clock.
task automatic IKAOPLL_write_simple (
    input logic i_TARGET_ADDR,
    input [7:0] i_WRITE_DATA
);
begin
    @(posedge phiMref) A0 = i_TARGET_ADDR;
    @(negedge phiMref) CS_n = 1'b0;
    @(posedge phiMref) DIN = i_WRITE_DATA;
    @(negedge phiMref) WR_n = 1'b0;
    @(posedge phiMref); // hold 1 phi
    @(negedge phiMref) WR_n = 1'b1;
                       CS_n = 1'b1;
    @(posedge phiMref) DIN = 8'hZZ;
end
endtask

`define AD #150
`define DD #800

// Ensure the VCD is opened from an initial block
initial begin
    $dumpfile("dump.vcd");
    $dumpvars(0, IKAOPLL_tb);
end

// Include the generated events fragment from tests/
// (compile with iverilog -Itests so `include finds tests/events_csv_tb.v)
`include "events_csv_tb.v"

// The original Verilator-style task uses 'ref' ports which Icarus doesn't support.
// Keep it available only when not compiling for Icarus (guarded).
`ifndef IVERILOG
task automatic IKAOPLL_write (
    input               i_TARGET_ADDR,
    input       [7:0]   i_WRITE_DATA,
    ref logic           i_CLK,
    ref logic           o_CS_n,
    ref logic           o_WR_n,
    ref logic           o_A0,
    ref logic   [7:0]   o_DATA
); begin
    @(posedge i_CLK) o_A0 = i_TARGET_ADDR;
    @(negedge i_CLK) o_CS_n = 1'b0;
    @(posedge i_CLK) o_DATA = i_WRITE_DATA;
    @(negedge i_CLK) o_WR_n = 1'b0;
    @(posedge i_CLK) ;
    @(negedge i_CLK) o_WR_n = 1'b1;
                     o_CS_n = 1'b1;
    @(posedge i_CLK) o_DATA = 8'hZZ;
end endtask
`endif

endmodule